#组件信息
app: bilibili
component: scf # (必填) 引用 component 的名称，当前用到的是 tencent-scf 组件
name: scfdemo # (必填) 创建的实例名称，请修改成您的实例名称

#B站自动领取经验
inputs:
  name: BiliExp #函数名称
  namespace: bilibili
  src: ../  #代码路径
  handler: BiliExp.main_handler #入口
  runtime: Python3.6 # 云函数运行时的环境
  region: ap-shanghai # 云函数所在区域
  description: 'B站自动领取经验'
  timeout: 60
  events: # 触发器
    - timer: # 定时触发器
        name: #触发器名称，默认timer-${name}-${stage}
        parameters:
          cronExpression: '0 20 16 * * *' 
          enable: true