name: "E-jd"
on:
  push:
    branches:
      - dockerjs
  workflow_dispatch:
  watch:
        types: [started]
  repository_dispatch:
        types: build_image_E_jd
  
  
jobs:
  build:
    runs-on: ubuntu-latest
    name: jd
    steps:
      - name: Checkout master
        uses: actions/checkout@master
      - name: Build and publish image
        uses: ilteoood/docker_buildx@master
        with:
          publish: true
          imageName: k1483162508/jd
          dockerFile: Edev/Dockerfile
          platform: linux/amd64,linux/arm64,linux/arm/v7
          tag: E
          dockerUser: ${{ secrets.DOCKER_USERNAME }}
          dockerPassword: ${{ secrets.DOCKER_PASSWORD }}