name: 'run BiliExp'

on:
  schedule:
    - cron: '0 4 * * *' #中午12:00执行，修改时注意时区
  watch:
    types: started
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id != 67217225 || github.event_name == 'workflow_dispatch'
    steps:
    - uses: actions/checkout@v2
      with: 
        ref: ${{ github.event.repository.default_branch }}

    - uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/run_in_Actions/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: 执行BiliExp
      run: bash ./run_in_Actions/run_BiliExp.sh
      env:
          ADVCONFIG: ${{ secrets.ADVCONFIG }}
          BILICONFIG: ${{ secrets.BILICONFIG }}
          PUSH_MESSAGE: ${{ secrets.PUSH_MESSAGE }}
